.TH BINHEX L "December 1990"
.UC
.SH NAME
binhex \- convert CAP aufs file(s) to Binhex 4.0 Unix file(s)
unxbin \- ditto but for *.{rsrc,data,info} format files
.SH SYNOPSIS
.B binhex
file ...
.br
.B unxbin
file ...
.br
.SH DESCRIPTION
.I Binhex
converts CAP aufs file(s) to BinHex 4.0 format and stores them
as Unix text (i.e. using Unix LF not Mac CR).
.I Unxbin
does the same but for *.{rsrc,data,info} format files.
.SH AUTHORS
binhex: Nigel Perry (np@doc.ic.ac.uk), based on
.br
unxbin: David Gentzel, Lexeme Corporation

