.TH CAPIT L "Decemeber 1990"
.UC
.SH NAME
capit \- convert a MacBinary file into a CAP aufs one.
.SH SYNOPSIS
.B capit
[
.B \-v
] file ...
.br
.SH DESCRIPTION
.I Capit
converts files from MacBinary to CAP aufs format and writes them to the current directory,
which should be a CAP aufs folder.
.SH OPTION
.TP
.B \-v
Verbose option.  Causes 
.I capit
to list name of each file converted.
.SH AUTHOR
Nigel Perry (np@doc.ic.ac.uk) based on macbin by John M. Sellens (jmsellens@watdragon.uwaterloo.ca).
