.TH CLEANUP L "December 1990"
.UC
.SH NAME
cleanup \- cleanup the current CAP aufs folder
.SH SYNOPSIS
.B cleanup
.SH DESCRIPTION
.I Cleanup
removes orphaned files stored in the hidden directories of a CAP aufs folder.
These occur when Unix commands such as mv & rm are used on CAp aufs files.
.SH AUTHOR
Nigel Perry (np@doc.ic.ac.uk)
