.TH DRAG L "December 1990"
.UC
.SH NAME
drag \- rename/move CAP aufs file(s)
.SH SYNOPSIS
.B drag
file file
.br
.B drag
f1 f2 ... folder
.SH DESCRIPTION
.I Drag
renames a CAP aufs file, or if there are multiple arguments moves CAP aufs files from one folder to another.
Do not use
.I mv
to rename/move files as this does not handle the hidden CAP aufs files.
.SH AUTHOR
Nigel Perry (np@doc.ic.ac.uk)
