.TH M2U L "December 1990"
.UC
.SH NAME
m2u \- convert file from Mac to Unix text
.br
u2m \- convert file from Unix to Mac text
.SH SYNOPSIS
.B m2u
file ...
.br
.B u2m
file ...
.SH DESCRIPTION
These commands convert files between Mac & Unix text formats i.e.
they convert CR's to LF's and vice versa.
.SH AUTHOR
Nigel Perry (np@doc.ic.ac.uk)
