.TH MACP L "December 1990"
.UC
.SH NAME
macp \- list an CAP aufs file
.SH SYNOPSIS
.B macp
file ...
.SH DESCRIPTION
.I Macp
lists the given files using your standard pager, obtained from $PAGER, which is usually
.I more
or
.I less .
Do not use the Unix pagers directly as CAP aufs files use CR and not LF as end of line.
.SH AUTHOR
Nigel Perry (np@doc.ic.ac.uk)
